
include::../../header.adoc[]

= Wish list

Mis à part tous les bugs qui restent encore, l'applicaton fonctionne un peu mieux. 

Voici quelques pistes que l'on pourrait encore suivre.

== Web service

Les web services et le json sont très à la mode.

Nous aimerions disposer de la liste des recettes via un service REST

.REST (Representational state transfer)
****
REST est un pattern de construction de service web basé sur un travail universitaire (pas de norme ou spécification).

Il repose intensivement sur le protocol HTTP et notamment sur ses méthodes GET, POST, PUT et DELETE.

On navigue ainsi dans les services un peu comme on naviguerait dans les pages web.

Plus de détails dans http://www.amazon.fr/RESTful-Web-Services-Leonard-Richardson/dp/0596529260[RESTful Web Services].
****

On souhaite avoir les 2 mappings suivant :

* /api/recipes : la liste paginée (paramètre page=xxx) des recettes, ordonancées par date descendante (les plus récentes en premier)
* /api/recipes/{id} : une recette

Ces pages n'affichent pas du html mais servent du json.

⇰ Voici la liste des choses à faire :

* Ajoutez un `ApiController` avec ces 2 mappings
* Trouvez comment renvoyer du json depuis le Controller
* Ajoutez ou modifier des méthodes dans `RecipeService`
* Mettez en place des tests pour ce Controller

== Groovy

http://groovy-lang.org/index.html[Groovy] est un language alternatif pour la jvm.

Il existe pas mal de http://www.groovy-lang.org/differences.html[différences] entre java et groovy.
Groovy essaye d'être le plus naturel possible pour des développeurs java.

Voici les différences clées :

* Tous les packages courants sont importés par défaut : java.io.* java.lang.* ...
* Groovy ajoute beaucoup de méthodes utilitaire au jdk
* Par défaut, tout est public (au lieu de package private en java)
* Java 8 a ajouté les lambdas mais Groovy supporte les closures depuis bien longtemps
* Groovy fait du http://docs.groovy-lang.org/latest/html/documentation/index.html#_string_interpolation[String interpolation]
* == fonctionne comme il devrait

.les languages de la JVM
****
Apart from the https://en.wikipedia.org/wiki/Java_(programming_language)[Java language] itself, the most common or well-known JVM languages are:

* https://en.wikipedia.org/wiki/Clojure[Clojure], a functional Lisp dialect with focus on simplicity and concurrency
* https://en.wikipedia.org/wiki/Groovy_(programming_language)[Groovy], a programming and scripting language
* https://en.wikipedia.org/wiki/Scala_(programming_language)[Scala], an object-oriented functional programming
* https://en.wikipedia.org/wiki/JRuby[JRuby], an implementation of https://en.wikipedia.org/wiki/Ruby_(programming_language)[Ruby]
* https://en.wikipedia.org/wiki/Kotlin_(programming_language)[Kotlin], a statically-typed language from JetBrains, the developers of IntelliJ IDEA
* https://en.wikipedia.org/wiki/Jython[Jython], an implementation of https://en.wikipedia.org/wiki/Python_(programming_language)[Python]

source https://en.wikipedia.org/wiki/List_of_JVM_languages
****

Nous allons reprendre quelques parties du code afin de voir ce que pourrait apporter Groovy.

⇰ Afin de pouvoir faire du groovy avec gradle, on ajoute le https://docs.gradle.org/current/userguide/groovy_plugin.html[plugin groovy] en plus de java.

[source,java]
----
apply plugin: 'java'
apply plugin: 'groovy'
----

⇰ Il faut aussi rajouter la lib groovy dans les dépendances et faire un refresh du projet gradle dans Intellij.

[source,java]
----
compile 'org.codehaus.groovy:groovy-all:2.4.3:indy'
----

⇰ Par défaut, le plugin groovy va chercher ses sources dans src/main/groovy et les tests dans src/test/groovy. Pour ne pas avoir à tout changer et faire tout compiler par groovy, on ajoute la configuration suivante.

[source,java]
----
sourceSets {
    main {
        java {
            srcDirs = [] <1>
        }
        groovy {
            srcDirs = ['src/main/java'] <2>
        }
    }
    test {
        java {
            srcDirs = []
        }
        groovy {
            srcDirs = ['src/test/java']
        }
    }
}
----
<1> Le compilateur java ne compile plus rien
<2> Le compilateur groovy compile les .java et .groovy dans src/main/java

=== Test en Groovy

On va regarder ce que cela peut donner dans un test en premier.

⇰ Renommez `RecipeServiceTest.java` en `RecipeServiceTest.groovy` (Refactor > Rename File).

⇰ Dans `RecipeServiceTest` la méthode save peut devenir

[source,java]
----
@Test
void save() { <1>
    recipeService.save(new Recipe(title: 'test recipe')) <2>

    assert recipeCollection.findOne().as(Recipe).title == 'test recipe' <3>
}
----
<1> La méthode est public par défaut
<2> Contructeur avec une Map, point virgule optionnel
<3> .class optionnel, title qui équivaut à getTitle(), assert et == font un http://docs.groovy-lang.org/next/html/documentation/core-testing-guide.html#_power_assertions[power assert]

C'est beaucoup plus compacte et surtout beaucoup plus lisible. Faites la même chose avec toutes les méthodes de cette classe.

Voici quelques autres idées.

.method name

En groovy, le nom de la méthode peut être une chaîne de caractères.

[source,java]
----
public void findByIdWithInvalidId()
----

⇰ Peut devenir

[source,java]
----
public void 'findById with invalid id'()
----

C'est peu pratique pour une méthode qu'on appelle. C'est beaucoup plus lisible pour des tests.

.n.times

[source,java]
----
recipeService.save(new Recipe())
recipeService.save(new Recipe())
recipeService.save(new Recipe())
recipeService.save(new Recipe())
recipeService.save(new Recipe())
----

⇰ Peut devenir

[source,java]
----
5.times { recipeService.save(new Recipe()) }
----

.size() marche sur les Iterable

[source,java]
----
Assert.assertEquals(5, stream(recipeService.findByQuery(new PageQuery()).spliterator(), false).count())
----

⇰ Devient

[source,java]
----
assert recipeService.findByQuery(new PageQuery()).size() == 5
----

.liste

[source,java]
----
new Recipe().withTags("tag1", "tag2")
----

⇰ Peut s'écrire plus simplement

[source,java]
----
new Recipe(tags: ['tag1', 'tag2'])
----

=== Dans le code

La volonté d'écrire du code très lisible dans les test fait de groovy un language de choix pour cela.

Mais puisque Groovy permet d'écrire du code compact et lisible, pourquoi ne pas en profiter dans les services et controllers ?

.Language dynamique vs Language statique
****
Les languages dynamiques sont plus souples et plus puissants.

Par contre, la flexibilité a un coût : moins d'erreurs peuvent être relevées au moment de la compilation.

En Groovy, savoir si une méthode existe sur un object se fait au runtime.

Il existe une annotation http://docs.groovy-lang.org/latest/html/gapi/groovy/transform/CompileStatic.html[@CompileStatic] qui permet de rétablir les checks au moment de la compilation.
****

Passez `IndexController` en groovy et appliquer les règles précédantes et suivantes, afin de simplifier le code.

IMPORTANT: Une liste en Groovy s'écrit `["/index", "/"]` et non `{"/index", "/"}`

.ModelMap

[source,java]
----
model.put("columns", randomColumns());
----

⇰ model étant une Map, on peut écrire

[source,java]
----
model.columns = randomColumns()
----

.Implicit return

Le return est implicite en Groovy

[source,java]
----
return "index";
----

⇰ peut s'écrire

[source,java]
----
'index'
----

En Groovy, une méthode retourne par défaut la dernière valeur évaluée.

.Groovy truth

[source,java]
----
if (recipe == null) {
    throw new ResourceNotFoundException();
}
----

⇰ Le test de non nullité peut être simplifié en

[source,java]
----
if (!recipe) {
    throw new ResourceNotFoundException()
}
----

.Are you elvish ?

Nous n'avons pas d'opérateur ternaire dans notre code, mais groovy permet d'utiliser le très sympathique http://docs.groovy-lang.org/docs/groovy-2.5.2/html/documentation/#_elvis_operator[opérateur elvis].

=== Groovy or not Groovy ?

Groovy a ses forces et faiblesses comme tous les languages.

Sans couverture de test, c'est assez dangereux de faire du Groovy.

Dans le web, c'est un language et un écosystème très plaisant.

Il existe aussi un framework web basé sur Spring Boot : https://grails.org/[Grails]

== Tests Selenium

Selenium est une librairie en java (qui existe dans beaucoup de languages) et des drivers pour les principaux naviagteurs web.

Elle permet de piloter le navigateur et ainsi de simuler un utilisateur du site.

On peut donc écrire des tests qui s'adressent au produit final et non à un morceau de code.

.Les libs

On ajoute les librairies nécessaires

----
testCompile 'org.seleniumhq.selenium:selenium-java:2.48.2' <1>
testCompile 'org.fluentlenium:fluentlenium-core:0.10.3' <2>
----
<1> Dernière librairie selenium (attention, la version change souvent et les vieilles versions deviennent vite obsolètes)
<2> Une librairie (https://github.com/FluentLenium/FluentLenium[fluentlenium]) pour simplifier l'écriture des tests

On va profiter d'avoir introduit groovy pour écrire nos tests simplement.

.Premier test

On ajoute la classe `PlublicTest.groovy` dans le package `fr.cmm.selenium`

[source,java]
----
import org.fluentlenium.adapter.FluentTest
import org.junit.Test

class PlublicTest extends FluentTest {
    @Test
    void 'visit home page'() {
        goTo 'http://localhost:8080/' <1>

        assert $('h1').text == 'Des recettes, des idées pour déguster' <2>
    }
}
----
<1> En groovy les parenthèse sont optionnelles
<2> Synthaxe à la jquery avec le $

Si on exécute le test, cela doit ouvrir un firefox, aller sur la home et vérifier que le titre est correct.

.La suite

Les test d'interface sont souvent difficiles et instables car ils reposent sur l'arbre DOM ou sûr des interactions avec celui-ci (comme des clicks de souris).

Cependant, ils ont une valeur extraordinaire car ils testent le produit fini. Ils sont moins nombreux que les tests unitaires, mais tout aussi importants.

Avec votre connaissance du site, que devrait on tester ?

* le nombre de recettes en home
* la navigation vers la page de recette
* que la recette du moment est bien disponible
* que le moteur de recherche fonctionne bien
* que l'on peut se logguer et aller éditer une recette
* que la recette est bien modifiée sur le site après édition

== More ?

Avec un peu d'idées, le développement d'une application web ne finit jamais.

On pourrait rajouter des commentaires, un système de note ou de like, proposer du sharing social...

Chaque fonctionnalité peut paraitre simple au départ et devenir complexe quand on rentre dans les détails.

Maintenir un code base propre est important afin d'être capable de faire évoluer son projet continuellement.

